### ISSUE TITLE
FlipTableConverters#fromResultSet is not public

### ISSUE THREAD

**Issue by sniffertine** [JakeWharton/flip-tables#22] opened 2020-02-07 19:18 UTC

**Comment by JakeWharton** [comment] 2020-02-07 20:14
Dupe of #11. What you're actually asking for is a release! Let me do that, instead.

**Closed by JakeWharton** 2020-02-07 20:14 UTC

**Comment by sniffertine** [comment] 2020-02-07 20:20
indeed. sorry for dupping

**Comment by JakeWharton** [comment] 2020-02-07 20:24
No problem! I have _clearly_ dropped the ball on getting a new release out.

**Comment by JakeWharton** [comment] 2020-02-07 20:32
Released as 1.1.0. Should be available on Maven central in an hour.
